### PR TITLE
[SECURITY-946] AdvancedLdapLoginModule with rolesCtxDN="" can lead to...

### PR DESCRIPTION
**Pull request by TomasHofman**
...authentication failure

https://issues.jboss.org/browse/SECURITY-946

### CODE REVIEW

**Comment by darranl** [comment]
Please ensure any pull requests to this repository use Jira issues in the SECURITY- project in Jira - also as a community project please remove all JBEAP references.

**Comment by darranl** [comment]
Missing ACKs but is also referencing a JBEAP issue instead of a SECURITY issue.

There should be no references to JBEAP issues in this repository.

**Comment by TomasHofman** [comment]
JBEAP reference changed to SECURITY.

**Comment by baranowb** [comment]
ACKs are in. Is it good for mergE?

**Pull request merged**
